/* webpage.h - embedded configuration UI (served by webui.c) */
#ifndef PTWH_WEBPAGE_H
#define PTWH_WEBPAGE_H

static const char WEBPAGE_HTML[] =
"<!DOCTYPE html><html><head><meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>PicoTuner-WH</title><style>"
"body{font-family:sans-serif;margin:16px;max-width:780px;background:#111;color:#eee}"
"h1{font-size:1.3em}h2{font-size:1.05em;color:#6cf;margin:14px 0 4px}"
"fieldset{border:1px solid #444;border-radius:6px;margin:6px 0;padding:8px}"
"label{display:inline-block;min-width:120px}"
"input,select{background:#222;color:#eee;border:1px solid #555;border-radius:4px;padding:3px;margin:2px}"
"button{background:#264;color:#fff;border:0;border-radius:4px;padding:6px 12px;margin:4px 2px;cursor:pointer}"
"button.warn{background:#833}"
"pre{background:#000;padding:8px;border-radius:6px;overflow:auto;font-size:12px}"
"</style></head><body>"
"<h1>PicoTuner-WH</h1>"
"<pre id='status'>loading...</pre>"
"<h2>Network</h2><fieldset>"
"<div><label>Mode</label><select id='dhcp' onchange='ipmode()'>"
"<option value='1'>DHCP</option><option value='0'>Static</option></select></div>"
"<div id='sf'>"
"<div><label>IP</label><input id='ip' size='15'></div>"
"<div><label>Mask</label><input id='sn' size='15'></div>"
"<div><label>Gateway</label><input id='gw' size='15'></div>"
"<div><label>DNS</label><input id='dns' size='15'></div></div>"
"<div><label>Hostname</label><input id='hostname' size='20'></div>"
"<div><label>Base IP port</label><input id='baseipport' size='6'></div>"
"<div><label>TS flash LEDs</label><select id='tsflash'><option value='1'>on</option><option value='0'>off</option></select></div>"
"<div><label>DHCP debug</label><select id='debug_dhcp'><option value='0'>off</option><option value='1'>on</option></select></div>"
"<div><label>LNB at boot</label><select id='lnb_autostart'><option value='0'>off</option><option value='1'>on</option></select></div>"
"<button onclick='saveCfg()'>Save &amp; reboot</button></fieldset>"
"<h2>LNB power</h2><fieldset>"
"<div><label>RX1 (X)</label><select id='lnbx'>"
"<option value='0'>off</option><option value='1'>13V</option><option value='2'>18V</option>"
"<option value='3'>13V + 22k</option><option value='4'>18V + 22k</option></select>"
"<button onclick='setLnb(1)'>Apply</button></div>"
"<div><label>RX2 (Y)</label><select id='lnby'>"
"<option value='0'>off</option><option value='1'>13V</option><option value='2'>18V</option>"
"<option value='3'>13V + 22k</option><option value='4'>18V + 22k</option></select>"
"<button onclick='setLnb(2)'>Apply</button></div></fieldset>"
"<h2>Tune</h2><fieldset>"
"<div><label>Receiver</label><select id='trx'><option value='1'>RX1</option><option value='2'>RX2</option></select>"
"<label>Freq (kHz)</label><input id='tfreq' size='9' value='10496708'>"
"<label>LO (kHz)</label><input id='tlo' size='9' value='9750000'>"
"<label>SR (kS)</label><input id='tsr' size='5' value='333'>"
"<label>Input</label><select id='tfplug'><option>A</option><option>B</option></select>"
"<button onclick='tune()'>Tune</button></div></fieldset>"
"<h2>Tuner chip (STV6120)</h2><fieldset>"
"<div><label>Receiver</label><select id='nrx'><option value='1'>RX1</option><option value='2'>RX2</option></select>"
"<label>RF input</label><select id='ninput'><option value='0'>RF A</option><option value='1'>RF B</option><option value='2'>RF C</option><option value='3'>RF D</option></select>"
"<label>Baseband gain</label><select id='nbb'><option>0</option><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option><option>6</option><option>7</option><option>8</option></select>"
"<button onclick='setNim(\"in\")'>Set input</button><button onclick='setNim(\"bb\")'>Set gain</button></div>"
"</fieldset>"
"<h2>LNA (STVVGLNA)</h2><fieldset>"
"<div><label>LNA</label><select id='lna'><option value='0'>LNA0</option><option value='1'>LNA1</option></select>"
"<label>Gain VGO</label><input id='lnagain' size='3' value='0'>"
"<label>AGC mode</label><select id='lnamode'><option value='0'>auto track</option><option value='1'>auto request</option><option value='2'>min gain int</option><option value='3'>max gain int</option><option value='4'>ext</option><option value='5'>loop ext</option><option value='6'>min ext</option><option value='7'>max ext</option></select>"
"<label>RFAGC pref</label><select id='lnapref'><option value='0'>-25dBm</option><option value='1'>-24dBm</option><option value='2'>-23dBm</option><option value='3'>-22dBm</option><option value='4'>-21dBm</option><option value='5'>-20dBm</option><option value='6'>-19dBm</option><option value='7'>-18dBm</option></select>"
"<button onclick='setNim(\"lna\")'>Apply LNA</button></div></fieldset>"
"<h2>DiSEqC / 22kHz / roll-off</h2><fieldset>"
"<div><label>Receiver</label><select id='drx'><option value='1'>RX1</option><option value='2'>RX2</option></select>"
"<label>22kHz</label><select id='dtone'><option value='1'>on</option><option value='0'>off</option></select>"
"<button onclick='setTone()'>Set tone</button>"
"<label>Roll-off ctrl</label><input id='droll' size='3' value='0'><button onclick='setRoll()'>Set</button></div>"
"<div><label>DiSEqC (hex)</label><input id='dhex' size='40' value='E0 10 38 F0'>"
"<button onclick='sendDiseqc()'>Send</button></div></fieldset>"
"<h2>Register access</h2><fieldset>"
"<div><label>Device</label><select id='rdev'><option value='0'>STV0910 demod</option><option value='1'>STV6120 tuner</option><option value='2'>STVVGLNA</option></select>"
"<label>Addr (LNA)</label><input id='raddr' size='4' value='0xCE'></div>"
"<div><label>Reg (hex)</label><input id='rreg' size='6' value='0x00'>"
"<label>Val (hex)</label><input id='rval' size='6' value='0x00'>"
"<button onclick='regRead()'>Read</button><button onclick='regWrite()'>Write</button></div>"
"<pre id='regres'>-</pre></fieldset>"
"<h2>System</h2><fieldset>"
"<button onclick='act(\"/api/reboot\",\"mode=0\")'>Reboot</button>"
"<button class='warn' onclick='act(\"/api/reboot\",\"mode=1\")'>Reset &amp; reboot</button>"
"<button onclick='act(\"/api/reboot\",\"mode=2\")'>BOOTSEL</button></fieldset>"
"<script>"
"function q(i){return document.getElementById(i);}"
"function ipmode(){q('sf').style.display=(q('dhcp').value=='1')?'none':'block';}"
"function post(u,b,cb){fetch(u,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:b})"
".then(function(r){return r.json();}).then(cb).catch(function(e){alert('error '+e);});}"
"function refresh(){fetch('/api/status').then(function(r){return r.json();}).then(function(d){"
"q('status').textContent=JSON.stringify(d,null,1);}).catch(function(){q('status').textContent='no response';});}"
"function loadCfg(){fetch('/api/config').then(function(r){return r.json();}).then(function(d){"
"q('dhcp').value=d.dhcp;q('ip').value=d.ip;q('sn').value=d.sn;q('gw').value=d.gw;q('dns').value=d.dns;"
"q('hostname').value=d.hostname;q('baseipport').value=d.baseipport;q('tsflash').value=d.tsflash;"
"q('debug_dhcp').value=d.debug_dhcp;q('lnb_autostart').value=d.lnb_autostart;"
"q('lnbx').value=d.lnb_x;q('lnby').value=d.lnb_y;ipmode();});}"
"function saveCfg(){var b='dhcp='+q('dhcp').value+'&ip='+q('ip').value+'&sn='+q('sn').value"
"+'&gw='+q('gw').value+'&dns='+q('dns').value+'&hostname='+encodeURIComponent(q('hostname').value)"
"+'&baseipport='+q('baseipport').value+'&tsflash='+q('tsflash').value+'&debug_dhcp='+q('debug_dhcp').value"
"+'&lnb_x='+q('lnbx').value+'&lnb_y='+q('lnby').value+'&lnb_autostart='+q('lnb_autostart').value;"
"post('/api/config',b,function(d){alert(d.msg);});}"
"function setLnb(r){var s=(r==1)?q('lnbx').value:q('lnby').value;"
"post('/api/lnb','rx='+r+'&state='+s,function(d){alert(d.msg);refresh();});}"
"function tune(){var b='rx='+q('trx').value+'&freq='+q('tfreq').value+'&lo='+q('tlo').value"
"+'&sr='+q('tsr').value+'&fplug='+q('tfplug').value;post('/api/tune',b,function(d){alert(d.msg);});}"
"function act(u,b){post(u,b,function(d){alert(d.msg);});}"
"function setNim(k){var b='';"
"if(k=='in'){b='rx='+q('nrx').value+'&input='+q('ninput').value;}"
"else if(k=='bb'){b='bbgain='+q('nbb').value;}"
"else if(k=='lna'){b='lna='+q('lna').value+'&gain='+q('lnagain').value+'&mode='+q('lnamode').value+'&pref='+q('lnapref').value;}"
"post('/api/nim',b,function(d){q('regres').textContent=d.msg;alert(d.msg);});}"
"function setTone(){post('/api/nim','rx='+q('drx').value+'&tone='+q('dtone').value,function(d){q('regres').textContent=d.msg;});}"
"function setRoll(){post('/api/nim','rx='+q('drx').value+'&rolloff='+q('droll').value,function(d){q('regres').textContent=d.msg;});}"
"function sendDiseqc(){post('/api/diseqc','rx='+q('drx').value+'&data='+encodeURIComponent(q('dhex').value),function(d){q('regres').textContent=d.msg;});}"
"function regRead(){fetch('/api/reg?dev='+q('rdev').value+'&addr='+parseInt(q('raddr').value,0)"
"+'&reg='+q('rreg').value).then(function(r){return r.json();}).then(function(d){"
"q('regres').textContent='read dev='+d.dev+' reg='+d.reg+' -> '+d.val+' (err '+d.err+')';});}"
"function regWrite(){var b='dev='+q('rdev').value+'&addr='+parseInt(q('raddr').value,0)"
"+'&reg='+q('rreg').value+'&val='+q('rval').value;post('/api/reg',b,function(d){"
"q('regres').textContent=JSON.stringify(d);});}"
"loadCfg();refresh();setInterval(refresh,2000);"
"</script></body></html>";

#endif
